[0.6.x] cherry pick ambient changes (#2477)
* Refactor: AmbientAware API change (#2472)

This change refactors the `AmbientAware` API to make it more intuitive and easier to use.

The following changes were made:

- The `AmbientAware` composable moves to the screen level
- The `AmbientStateUpdate` class was merged into `AmbientState`.
- The `AmbientState` sealed interface now has a data object `Interactive` and a data class `Ambient` to store AmbientDetails, as well as Inactive.

---------

(cherry picked from commit f8ccc682f6fcbb5d1fcd97276491992697fbd5a1)

* Fix: Handle missing AmbientLifecycleObserver in Robolectric (#2474)

* Fix: Handle missing AmbientLifecycleObserver in Robolectric

Handles missing AmbientLifecycleObserver in Robolectric tests by catching NoClassDefFoundError and returning null instead of crashing. This allows ambient-aware composables to be tested in Robolectric without requiring a real device or emulator.

---------

(cherry picked from commit 6cd025b1f330c8594b071e2bb683ba7188ca44ac)